# ----
# Site

title: RaaS
description: RaaS API documentation.
url: https://digitalhumani.com/
google_analytics_key:
permalink: pretty
baseurl:

org_name: Digital Humani
is_DH: true
base_url: https://docs.digitalhumani.com # This site
site_url: https://digitalhumani.com # Marketing site
api_url: https://api.digitalhumani.com
dashboard_url: https://my.digitalhumani.com
dashboard_register_url: https://my.digitalhumani.com/register
logo_url: https://assets.dev.digitalhumani.com/org/logo.png
favicon_url: https://assets.dev.digitalhumani.com/org/favicon.ico
logo_css: "aspect-ratio: 1; width: 33%;"
sandbox_api: https://api.sandbox.digitalhumani.com/
sandbox_dashboard: https://my.sandbox.digitalhumani.com/
support_email: info@digitalhumani.com
intro_header: Welcome to the documentation for the [Digital Humani](https://digitalhumani.com/) API! We refer to this service as **RaaS**, or "Reforestation as as Service". It is a simple API for planting trees with trusted reforestation organizations.

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position_number: 1
  api:
    title: APIs
    position_number: 2
  appendix:
    title: Appendix
    position_number: 3

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "documentation"
    values:
      _hide_content: true
  - scope:
      type: "api"
    values:
      _hide_content: true
  - scope:
      type: "appendix"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
